### ISSUE TITLE
Use different precision for different color component

### ISSUE THREAD

**Issue by ai** [fpetrakov/convert-to-oklch#10]
1% of L, C, and H are different. So we should not have the same precision for every component.

I suggest:
- Use `x,x` for L
- `x,xxx` for C
- `x,x` for H

**Comment by fpetrakov** [comment]
Do you suggest to just use `toFixed(n)` on every component?

**Comment by ai** [comment]
I suggest to use different `n` (digits after `,`) for every component (because they have different max value).

Something like `oklch(50.5 0.051 350.5)`

**Comment by fpetrakov** [comment]
So just cut off without rounding?

**Comment by ai** [comment]
With rounding, of course

**Comment by fpetrakov** [comment]
@ai I guess it's done
