### ISSUE TITLE
Lightness not converted to a percentage

### ISSUE THREAD

**Issue by onlytherain** [fpetrakov/convert-to-oklch#13]
While attempting to convert css files containing `hex`, `hsl`, and `rgb` color spaces to `oklch`, I found in each instance only the C and H components were successfully converted.

L (lightness) failed to convert to a percentile value. The command used was:
```bash
npx convert-to-oklch ./colours/*.css -p 2
```
Convert-to-oklch version:- 1.2.7

Below is a small sampling (Before/After). As you will see, Lightness converted only to a decimal value, such as used in the `lch` colorspace; visually, the colours seem consistent.

Conversion to a percentage value, *required* for the `oklch` colorspace has not been performed:

**HEX Colorspace**:
```bash
# Before conversion
.hex_amethyst { color: color: #9966cc; }
.hex_android-green { color: #a4c639; }
.hex_antique-brass { color: #cd9575; }
.hex_antique-fuchsia { color: #915c83; }
.hex_apple-green { color: #8db600; }
.hex_apricot { color: #fbceb1; }

# After conversion
.hex_amethyst { color: oklch(0.6 0.2 310); }
.hex_android-green { color: oklch(0.8 0.2 120); }
.hex_antique-brass { color: oklch(0.7 0.1 51); }
.hex_antique-fuchsia { color: oklch(0.5 0.1 340); }
.hex_apple-green { color: oklch(0.7 0.2 120); }
.hex_apricot { color: oklch(0.9 0.1 54); }
```

**HSL Colorspace**:
```bash
# Before conversion
.hsl_amethyst { color: hsl(270, 50%, 60%); }
.hsl_android-green { color: hsl(74.5, 55.3%, 50%); }
.hsl_antique-brass { color: hsl(21.8, 46.8%, 63.1%); }
.hsl_antique-fuchsia { color: hsl(315.8, 22.4%, 46.5%); }
.hsl_apple-green { color: hsl(73.5, 100%, 35.7%); }
.hsl_apricot { color: hsl(23.5, 90.2%, 83.9%); }

# After conversion
.hsl_amethyst { color: oklch(0.6 0.2 310); }
.hsl_android-green { color: oklch(0.8 0.2 120); }
.hsl_antique-brass { color: oklch(0.7 0.1 51); }
.hsl_antique-fuchsia { color: oklch(0.5 0.1 340); }
.hsl_apple-green { color: oklch(0.7 0.2 120); }
.hsl_apricot { color: oklch(0.9 0.1 54); }
```

**RGB Colorspace**:
```bash
# Before conversion
.rgb_amethyst { color: rgb(153, 102, 204); }
.rgb_android-green { color: rgb(164, 198, 57); }
.rgb_antique-brass { color: rgb(205, 149, 117); }
.rgb_antique-fuchsia { color: rgb(145, 92, 131); }
.rgb_apple-green { color: rgb(141, 182, 0); }
.rgb_apricot { color: rgb(251, 206, 177); }

# After conversion
.rgb_amethyst { color: oklch(0.6 0.2 310); }
.rgb_android-green { color: oklch(0.8 0.2 120); }
.rgb_antique-brass { color: oklch(0.7 0.1 51); }
.rgb_antique-fuchsia { color: oklch(0.5 0.1 340); }
.rgb_apple-green { color: oklch(0.7 0.2 120); }
.rgb_apricot { color: oklch(0.9 0.1 54); }
```
I hope this brief description is sufficient to correct the issue. Thanks.

**Comment by fpetrakov** [comment]
Thanks for opening the issue. Just to clarify, you get
```css
.rgb_amethyst { color: oklch(0.6 0.2 310); }
```
but you want
```css
.rgb_amethyst { color: oklch(60% 0.2 310); }
```
If so, can you please provide a link to CSS specification where it states that L component is required to have a percentage value?

**Comment by fpetrakov** [comment]
Also I tried to reproduce it, but it didn't work out. I got percentage values:
```
# Before conversion
.hsl_amethyst { color: hsl(270, 50%, 60%); }
.hsl_android-green { color: hsl(74.5, 55.3%, 50%); }
.hsl_antique-brass { color: hsl(21.8, 46.8%, 63.1%); }
.hsl_antique-fuchsia { color: hsl(315.8, 22.4%, 46.5%); }
.hsl_apple-green { color: hsl(73.5, 100%, 35.7%); }
.hsl_apricot { color: hsl(23.5, 90.2%, 83.9%); }

# After conversion
.hsl_amethyst { color: oklch(61% 0.2 310); }
.hsl_android-green { color: oklch(78% 0.2 120); }
.hsl_antique-brass { color: oklch(72% 0.1 51); }
.hsl_antique-fuchsia { color: oklch(55% 0.1 340); }
.hsl_apple-green { color: oklch(72% 0.2 120); }
.hsl_apricot { color: oklch(88% 0.1 54); }
```

**Comment by fpetrakov** [comment]
Thanks for your detailed response. 

> In [CSS Color Module Level 4 - 9.2 Oklab and Oklch](https://www.w3.org/TR/css-color-4/#ok-lab) the reason for this is also stated:

There are also examples of L being a decimal value:
- https://www.w3.org/TR/css-color-4/#ex-oklch-samples
- https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch#l

> Like CIE Lab, there is a central lightness axis which is usually written as a unitless number in the range [0,1]; for compatibility with the rest of CSS, it is written as a percentage.

Can you please explain what compatibility problems does usage of a percentage value resolve? I couldn't find more detailed explanation of this statement. 

> Which versions of dependent packages are you using for testing? It may be possible that the issue lies with one of them. I'll check mine also, and we'll compare versions.

I have only 2 deps installed globally:

```
├── npm@10.2.0
└── pnpm@8.9.0
```  
I also tried to install colorjs.io and convert-to-oklch globally but it didn't work out again. I still get percentage values as intended

**Comment by fpetrakov** [comment]
> Could you define the environment you use to produce a successful outcome?

I guess the problem is that your global colorjs.io version is greater than the one used in the project and for some reason, they are conflicting or something like that :/

Could you delete colorjs.io from the global registry and try again?

**Comment by fpetrakov** [comment]
> The colorjs.io version (0.4.5) was identical to that automatically installed as a dependency of convert-to-oklch.

Oh, I just noticed that I forgot to publish a commit in which I've locked version of colorjs.io to 0.4.0. I think, you can update convert-to-oklch to the 1.2.8 version and try again.

> If not, please list the versions that you use which do produce the expected output.

As I said earlier, I don't have neither convert-to-oklch, nor colorjs insalled locally or globally. I just run it with `npx` as intended.

 I tried installing the same packages you listed with the same versions, but it didn't reproduce.

**Comment by onlytherain** [comment]
>Oh, I just noticed that I forgot to publish a commit in which I've locked version of colorjs.io to 0.4.0. I think, you can update convert-to-oklch to the 1.2.8 version and try again.

I can confirm that locking in `colorjs.io 0.4.0` seems to have solved the issue;

`convert-to-oklch 1.2.8` now correctly uses percentage notation for L (Lightness) when converting hex, hsl, and rgb colorspaces to oklch.
