### ISSUE TITLE
Consider adjusting the decimal accuracy

### ISSUE THREAD

**Issue by pepelsbey** [fpetrakov/convert-to-oklch#6]
Thanks to the conversion fixed in the previous PR, I was able to try it out. And it turned out to be less useful than I thought.

Instead of the compact HEX, I got long decimals:

`#​24292f` vs. `oklch(0.2785 0.0132 253.04)`

So I thought maybe 4 decimal points might be way too accurate. But I honestly don't know how accurate it should be to represent the same color.

![image](https://user-images.githubusercontent.com/105274/204923138-b12df78a-cb5e-4a95-a330-9d1e7c352c9f.png)

**Comment by fpetrakov** [comment]
Hi, Vadim! Conversion is done with [colorjs](https://colorjs.io/) package by Lea Verou. I think it would be useful to have an option to change the precision of conversion. Moreover, colorjs [has](https://colorjs.io/docs/output.html#getting-a-string-representation-of-a-color) this option! It could look like smth like this:
```bash
npx convert-to-oklch --precision 3 // number of digits 
```

Maybe I will find time to implement it this week. Also, feel free to contribute if you have time. 

Thanks for PR!

**Comment by pepelsbey** [comment]
Thank you! The only question left is the default value. How did you pick it and could it be lower?
